import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Terms of Service | Docket',
  description: 'Terms and conditions for using Docket.',
  alternates: {
    canonical: '/terms',
  },
}

export default function TermsOfServicePage() {
  return (
    <article className="space-y-8">
      <header>
        <h1 className="font-headings text-2xl font-bold text-text">Terms of Service</h1>
        <p className="mt-1 text-sm text-muted">Last updated: March 18, 2026</p>
      </header>

      <section className="space-y-3">
        <h2 className="font-headings text-lg font-semibold text-text">1. Acceptance of Terms</h2>
        <p className="text-sm leading-relaxed text-text">
          By creating an account or using Docket (operated by JB Technologies LLC), you agree to be bound by
          these Terms of Service and our{' '}
          <a href="/privacy" className="text-accent hover:underline">Privacy Policy</a>.
          If you do not agree, do not use the service.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-headings text-lg font-semibold text-text">2. Service Description</h2>
        <p className="text-sm leading-relaxed text-text">
          Docket is an AI-powered invoice processing service. You upload invoices, our AI extracts structured
          data, you review and correct the extracted data, and then sync approved invoices as bills to your
          connected QuickBooks Online account.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-headings text-lg font-semibold text-text">3. Accounts</h2>
        <ul className="list-disc space-y-2 pl-5 text-sm leading-relaxed text-text">
          <li>You must be at least 18 years old or authorized to act on behalf of a business to use Docket.</li>
          <li>One account per person. You are responsible for maintaining the security of your login credentials.</li>
          <li>You must provide accurate and complete information when creating your account.</li>
          <li>You are responsible for all activity that occurs under your account.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="font-headings text-lg font-semibold text-text">4. Acceptable Use</h2>
        <p className="text-sm leading-relaxed text-text">You agree to use Docket only for:</p>
        <ul className="list-disc space-y-2 pl-5 text-sm leading-relaxed text-text">
          <li>Processing legitimate business invoices</li>
          <li>Lawful purposes in compliance with all applicable laws</li>
        </ul>
        <p className="text-sm leading-relaxed text-text">You agree not to:</p>
        <ul className="list-disc space-y-2 pl-5 text-sm leading-relaxed text-text">
          <li>Upload illegal, fraudulent, or misleading content</li>
          <li>Attempt to abuse, disrupt, or exploit the service</li>
          <li>Use automated scripts or bots to access the service without prior written consent</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="font-headings text-lg font-semibold text-text">5. Your Content</h2>
        <ul className="list-disc space-y-2 pl-5 text-sm leading-relaxed text-text">
          <li>You retain full ownership of all invoices and business data you upload to Docket.</li>
          <li>
            You grant JB Technologies LLC a limited, non-exclusive license to process your content solely for
            the purpose of providing the service (AI extraction, storage, and sync to your accounting system).
          </li>
          <li>
            We do not sell or share your invoice content with third parties except as necessary to provide the
            service (see our <a href="/privacy" className="text-accent hover:underline">Privacy Policy</a>).
          </li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="font-headings text-lg font-semibold text-text">6. AI-Assisted Processing</h2>
        <ul className="list-disc space-y-2 pl-5 text-sm leading-relaxed text-text">
          <li>Invoice extraction results are generated by artificial intelligence and may contain errors.</li>
          <li>
            You are responsible for reviewing all extracted data before approving and syncing it to QuickBooks.
          </li>
          <li>
            Docket is a tool to assist your invoice processing workflow. It is not a substitute for professional
            accounting judgment.
          </li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="font-headings text-lg font-semibold text-text">7. Third-Party Integrations</h2>
        <ul className="list-disc space-y-2 pl-5 text-sm leading-relaxed text-text">
          <li>
            Your QuickBooks Online connection is governed by Intuit&rsquo;s terms of service. We access your
            QuickBooks data to: (a) read your vendor list and chart of accounts for invoice mapping,
            (b) create bills from approved invoices, and (c) attach source documents to created bills.
            We do not read or modify other QuickBooks data.
          </li>
          <li>Subscription billing is processed by Stripe and governed by Stripe&rsquo;s terms of service.</li>
          <li>We facilitate these integrations but do not guarantee third-party service uptime or accuracy.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="font-headings text-lg font-semibold text-text">8. Billing &amp; Subscription</h2>
        <ul className="list-disc space-y-2 pl-5 text-sm leading-relaxed text-text">
          <li>Paid plans are billed monthly via Stripe.</li>
          <li>
            Design partner program: the first 10 users receive free access to all MVP features, capped at
            100 invoices per month.
          </li>
          <li>Cancellation takes effect at the end of your current billing period.</li>
          <li>We reserve the right to change pricing with 30 days&rsquo; notice via email.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="font-headings text-lg font-semibold text-text">9. Limitation of Liability</h2>
        <ul className="list-disc space-y-2 pl-5 text-sm leading-relaxed text-text">
          <li>Docket is provided &ldquo;as is&rdquo; and &ldquo;as available&rdquo; without warranties of any kind.</li>
          <li>
            JB Technologies LLC is not liable for errors in AI extraction, QuickBooks sync failures, or
            accounting decisions made based on extracted data.
          </li>
          <li>
            Our total liability to you for any claims arising from your use of Docket is limited to the
            fees you paid us in the 12 months preceding the claim.
          </li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="font-headings text-lg font-semibold text-text">10. Indemnification</h2>
        <p className="text-sm leading-relaxed text-text">
          You agree to indemnify and hold harmless JB Technologies LLC from any claims, damages, or expenses
          arising from: (a) your use of the service, (b) data you approve and sync to QuickBooks,
          or (c) your violation of these terms.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-headings text-lg font-semibold text-text">11. Termination</h2>
        <ul className="list-disc space-y-2 pl-5 text-sm leading-relaxed text-text">
          <li>Either party may terminate your account at any time.</li>
          <li>On termination, you may request deletion of your data by contacting us.</li>
          <li>We may suspend or terminate accounts that violate these terms without prior notice.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="font-headings text-lg font-semibold text-text">12. Dispute Resolution</h2>
        <ul className="list-disc space-y-2 pl-5 text-sm leading-relaxed text-text">
          <li>
            Any disputes arising from these terms or your use of Docket will be resolved by binding
            arbitration on an individual basis (not as a class action), with a carve-out for claims that
            qualify for small claims court.
          </li>
          <li>These terms are governed by the laws of the State of California.</li>
        </ul>
      </section>

      <section className="space-y-3">
        <h2 className="font-headings text-lg font-semibold text-text">13. Changes to Terms</h2>
        <p className="text-sm leading-relaxed text-text">
          We may update these Terms of Service from time to time. We will notify you of material changes by
          sending an email to the address associated with your account. Your continued use of Docket after
          such changes constitutes acceptance of the updated terms.
        </p>
      </section>

      <section className="space-y-3">
        <h2 className="font-headings text-lg font-semibold text-text">14. Contact</h2>
        <p className="text-sm leading-relaxed text-text">
          If you have questions about these Terms of Service, contact us at{' '}
          <a href="mailto:support@dockett.app" className="text-accent hover:underline">support@dockett.app</a>.
        </p>
        <p className="text-sm leading-relaxed text-text">
          JB Technologies LLC<br />
          dockett.app
        </p>
      </section>
    </article>
  )
}
